### ISSUE TITLE
关闭refresh的刷新状态

### ISSUE THREAD

**Issue by ColorfulCat** [CB-ysx/wanandroid-quickapp#1]
在组件上用 refreshing="{{isRefreshing}}"  就可以控制了。如下：
`<refresh class="refresh-div" onrefresh="refresh" refreshing="{{isRefreshing}}" offset="200">`

**Comment by charlieysx** [comment]
@ColorfulCat 好的，我想我大概明白为什么之前一直不行了，可能是没有加{{}}了，我试试，谢谢！

**Comment by charlieysx** [comment]
@ColorfulCat 刚试了下，不是这样加就可以，看了您的gank快应用代码，在“refresh”方法里加上“this.isRefreshing = e.refreshing”才可以
`refresh(evt) {
      this.isRefreshing = evt.refreshing;
      this.page = 0;
      this.getArticle();
    }
`
谢谢您的提示
