### ISSUE TITLE
想问下你的dev-tools是怎么打开的 我的都打开不了呢

### ISSUE THREAD

**Issue by pengxingyun** [CB-ysx/wanandroid-quickapp#4]
想问下你的dev-tools是怎么打开的 我的都打开不了呢 console打印不了东西

**Comment by charlieysx** [comment]
@pengxingyun 我是这样的：
`
npm run server -- --port 8080

npm run  watch

adb logcat -s JsConsole
`

然后再快应用调试器点击**开始调试**按钮，然后就可以进行开发及调试了

不过我浏览器调试很少用，因为调试页面加载比较慢，我一般直接**adb logcat -s JsConsole**看日志
