### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by fza3230200** [CB-ysx/wanandroid-quickapp#8]
源码下载下来之后,直接npm run build,失败是什么原因啊?还需要npm install??

**Comment by charlieysx** [comment]
@fza3230200 是的，先npm install安装依赖

**Comment by fza3230200** [comment]
@CB-ysx 请问您是用的哪个版本的node.js啊? 我run build 报错

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "D:\\nodeJS\\node.exe" "D:\\nodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wanandroid@1.0.0 build: `cross-env NODE_PLATFORM=na NODE_PHASE=dv webpack --config ./node_modules/hap-tools/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wanandroid@1.0.0 build script 'cross-env NODE_PLATFORM=na NODE_PHASE=dv webpack --config ./node_modules/hap-tools/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wanandroid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_PLATFORM=na NODE_PHASE=dv webpack --config ./node_modules/hap-tools/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wanandroid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wanandroid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\quickappProject\HelloWord\quickappwanandroid\wanandroid-quickapp\npm-debug.log

**Comment by charlieysx** [comment]
@fza3230200 8.2.0

**Comment by fza3230200** [comment]
编译成功后,发现底下的tabList跑顶部了,各个界面都没有展示,却有网络请求,你知道是什么原因吗

**Comment by charlieysx** [comment]
@fza3230200 您换个手机试试看？

**Comment by passself** [comment]
webpack.config.js 找不到是什么意思

**Comment by charlieysx** [comment]
@passself 如果报错遇到Cannot find module '.../webpack.config.js'，请重新执行一次hap update --force。这是由于高版本的npm在npm install时，会校验并删除了node_modules下部分文件夹，导致报错。而hap update --force会重新复制hap-tools文件夹到node_modules中
